// layout is common to the entire application. all components will be treated as childer

import '../styles/globals.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import  Nav from '../components/Nav/Nav';

// related to google fonts
const inter = Inter({ subsets: ['latin'] })

// for seo purpose
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Nav/>
        {children}
        
        </body>
    </html>
  )
}
