// layout is common to the entire application. all components will be treated as childer

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import  Link from 'next/link';

// related to google fonts
const inter = Inter({ subsets: ['latin'] })

// for seo purpose
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex  p-12" >
          <Link className='p-4' href={'/'}>Home</Link>
          <Link className='p-4' href={'/about'}>About</Link>
          <Link className='p-4' href={'/contact'}>Contact</Link>
          <Link className='p-4' href={'settings'}>Settings</Link>
        </nav>
        {children}
        
        </body>
    </html>
  )
}
